/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizapp;

/**
 *
 * @author sgupt
 */
public class GameWin extends javax.swing.JFrame {

    /**
     * Creates new form GameWin
     */
    public GameWin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsBG = new javax.swing.ButtonGroup();
        body = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        timerPanel = new javax.swing.JPanel();
        timerLabel = new javax.swing.JLabel();
        QuestionsPanel = new javax.swing.JPanel();
        questionPanel = new javax.swing.JPanel();
        q = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        optionPanelA = new javax.swing.JPanel();
        oA = new javax.swing.JRadioButton();
        optionA = new javax.swing.JLabel();
        optionPanelB = new javax.swing.JPanel();
        oB = new javax.swing.JRadioButton();
        optionB = new javax.swing.JLabel();
        optionPanelC = new javax.swing.JPanel();
        oC = new javax.swing.JRadioButton();
        optionC = new javax.swing.JLabel();
        optionPanelD = new javax.swing.JPanel();
        oD = new javax.swing.JRadioButton();
        optionD = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        nextBtn = new javax.swing.JPanel();
        nextBtnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(34, 43, 53));
        body.setForeground(new java.awt.Color(242, 242, 242));

        topPanel.setBackground(new java.awt.Color(34, 43, 53));
        topPanel.setForeground(new java.awt.Color(242, 242, 242));

        timerPanel.setBackground(new java.awt.Color(34, 43, 53));
        timerPanel.setForeground(new java.awt.Color(242, 242, 242));

        timerLabel.setBackground(new java.awt.Color(60, 63, 66));
        timerLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(242, 242, 242));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerLabel.setText("99");

        javax.swing.GroupLayout timerPanelLayout = new javax.swing.GroupLayout(timerPanel);
        timerPanel.setLayout(timerPanelLayout);
        timerPanelLayout.setHorizontalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        timerPanelLayout.setVerticalGroup(
            timerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        QuestionsPanel.setBackground(new java.awt.Color(34, 43, 53));
        QuestionsPanel.setForeground(new java.awt.Color(242, 242, 242));

        questionPanel.setBackground(new java.awt.Color(34, 43, 53));
        questionPanel.setForeground(new java.awt.Color(242, 242, 242));

        q.setBackground(new java.awt.Color(60, 63, 66));
        q.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        q.setForeground(new java.awt.Color(242, 242, 242));
        q.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        q.setText("99");

        question.setBackground(new java.awt.Color(60, 63, 66));
        question.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        question.setForeground(new java.awt.Color(242, 242, 242));
        question.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        question.setText("Question");

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(q, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        optionPanelA.setBackground(new java.awt.Color(34, 43, 53));
        optionPanelA.setForeground(new java.awt.Color(242, 242, 242));

        optionsBG.add(oA);

        optionA.setBackground(new java.awt.Color(60, 63, 66));
        optionA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionA.setForeground(new java.awt.Color(242, 242, 242));
        optionA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionA.setText("Option A");

        javax.swing.GroupLayout optionPanelALayout = new javax.swing.GroupLayout(optionPanelA);
        optionPanelA.setLayout(optionPanelALayout);
        optionPanelALayout.setHorizontalGroup(
            optionPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionPanelALayout.setVerticalGroup(
            optionPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionA, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(oA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        optionPanelB.setBackground(new java.awt.Color(34, 43, 53));
        optionPanelB.setForeground(new java.awt.Color(242, 242, 242));

        optionsBG.add(oB);

        optionB.setBackground(new java.awt.Color(60, 63, 66));
        optionB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionB.setForeground(new java.awt.Color(242, 242, 242));
        optionB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionB.setText("Option B");

        javax.swing.GroupLayout optionPanelBLayout = new javax.swing.GroupLayout(optionPanelB);
        optionPanelB.setLayout(optionPanelBLayout);
        optionPanelBLayout.setHorizontalGroup(
            optionPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionB, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionPanelBLayout.setVerticalGroup(
            optionPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionB, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(oB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        optionPanelC.setBackground(new java.awt.Color(34, 43, 53));
        optionPanelC.setForeground(new java.awt.Color(242, 242, 242));

        optionsBG.add(oC);

        optionC.setBackground(new java.awt.Color(60, 63, 66));
        optionC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionC.setForeground(new java.awt.Color(242, 242, 242));
        optionC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionC.setText("Option C");

        javax.swing.GroupLayout optionPanelCLayout = new javax.swing.GroupLayout(optionPanelC);
        optionPanelC.setLayout(optionPanelCLayout);
        optionPanelCLayout.setHorizontalGroup(
            optionPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionC, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionPanelCLayout.setVerticalGroup(
            optionPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionC, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(oC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        optionPanelD.setBackground(new java.awt.Color(34, 43, 53));
        optionPanelD.setForeground(new java.awt.Color(242, 242, 242));

        optionsBG.add(oD);

        optionD.setBackground(new java.awt.Color(60, 63, 66));
        optionD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionD.setForeground(new java.awt.Color(242, 242, 242));
        optionD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionD.setText("Option D");

        javax.swing.GroupLayout optionPanelDLayout = new javax.swing.GroupLayout(optionPanelD);
        optionPanelD.setLayout(optionPanelDLayout);
        optionPanelDLayout.setHorizontalGroup(
            optionPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionD, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionPanelDLayout.setVerticalGroup(
            optionPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionD, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(oD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout QuestionsPanelLayout = new javax.swing.GroupLayout(QuestionsPanel);
        QuestionsPanel.setLayout(QuestionsPanelLayout);
        QuestionsPanelLayout.setHorizontalGroup(
            QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionPanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionPanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionPanelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionPanelD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QuestionsPanelLayout.setVerticalGroup(
            QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bottomPanel.setBackground(new java.awt.Color(34, 43, 53));
        bottomPanel.setForeground(new java.awt.Color(242, 242, 242));

        nextBtn.setBackground(new java.awt.Color(34, 43, 53));
        nextBtn.setForeground(new java.awt.Color(242, 242, 242));

        nextBtnLabel.setBackground(new java.awt.Color(60, 63, 66));
        nextBtnLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nextBtnLabel.setForeground(new java.awt.Color(242, 242, 242));
        nextBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextBtnLabel.setText("NEXT");

        javax.swing.GroupLayout nextBtnLayout = new javax.swing.GroupLayout(nextBtn);
        nextBtn.setLayout(nextBtnLayout);
        nextBtnLayout.setHorizontalGroup(
            nextBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nextBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        nextBtnLayout.setVerticalGroup(
            nextBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nextBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuestionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuestionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuestionsPanel;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel bottomPanel1;
    private javax.swing.JPanel nextBtn;
    private javax.swing.JLabel nextBtnLabel;
    private javax.swing.JRadioButton oA;
    private javax.swing.JRadioButton oB;
    private javax.swing.JRadioButton oC;
    private javax.swing.JRadioButton oD;
    private javax.swing.JLabel optionA;
    private javax.swing.JLabel optionB;
    private javax.swing.JLabel optionC;
    private javax.swing.JLabel optionD;
    private javax.swing.JPanel optionPanelA;
    private javax.swing.JPanel optionPanelB;
    private javax.swing.JPanel optionPanelC;
    private javax.swing.JPanel optionPanelD;
    private javax.swing.ButtonGroup optionsBG;
    private javax.swing.JLabel q;
    private javax.swing.JLabel question;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JPanel timerPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
